main: dk.muj.derius.multiplier.DeriusMultiplier
name: Derius-Multiplier
version: 0.1_dev
#website: http://muj.dk/Derius/Mining
authors: [madus, ulumulu1510]
description: §eDerius multiplier
depend: [Derius-Core]
load: startup
