main: dk.muj.derius.multiplier.DeriusMultiplier
name: Derius-Multiplier
version: 0.1_dev
#website: http://muj.dk/Derius/Mining
authors: [Madus, Ulumulu1510]
description: <g>A multiplier for giving more or less experience for Derius skills.
depend: [Derius-Core]
load: startup
